spring:
  application:
    name: ${APP_NAME:demo}

feign:
  client:
    config:
      default:
        errorDecoder: tw.com.softleader.demo.codec.FeignClientErrorDecoder

client:
  addr: ${CLIENT_ADDR:demo}
